"""ReportGenerator — turns a transcript + supervisor feedback into a family-facing report."""

from __future__ import annotations

import os
from datetime import datetime
from typing import Any

from ..agents.base import BaseAgent
from ..seniors.store import SeniorProfile


class ReportGenerator(BaseAgent):
    """LLM-backed generator that distills a transcript into a warm, factual report."""

    role = "report_generator"
    description = "Writes a daily report for the family based on the call transcript."

    def __init__(self, model: str | None = None):
        model = model or os.getenv("REPORT_MODEL")
        super().__init__(model=model, temperature=0.3, max_tokens=1200)

    def generate(
        self,
        profile: SeniorProfile,
        transcript_md: str,
        supervisor_feedback: dict[str, Any],
    ) -> str:
        family_name = profile.family_contact.get("name", "Family")
        senior_notes = "\n".join(f"- {n}" for n in supervisor_feedback.get("senior_notes", [])) or "(none)"

        prompt = f"""You are writing a short daily report for the family of an elderly person who just received a wellness check-in call.

## About this senior

{profile.to_summary()}

## Full call transcript

{transcript_md}

## Notes the supervisor flagged about the call

{senior_notes}

## Your task

Write a clear, warm, factual report addressed to "{family_name}" about how today's call went.

Use this exact structure (markdown):

# Daily Wellness Report — {profile.name} — {datetime.now().strftime("%Y-%m-%d")}

## How {profile.name} is feeling today
(2-3 sentences on overall mood and emotional tone)

## Health
(Anything they reported — pain, sleep, medications, energy. Tie back to known conditions when relevant. NEVER invent symptoms.)

## Safety & home
(Whether they ate, whether anyone visited, anything notable about home. If nothing — say "nothing of concern.")

## Highlights from the conversation
(2-3 short bullets — moments that mattered: things they shared about family, garden, memories, etc.)

## Anything worth a follow-up
(Concrete things the family might want to act on or simply be aware of. If nothing — say "nothing pressing.")

---

_Generated by your wellness call service. Next call: tomorrow._

## Rules

- Do NOT invent details that aren't in the transcript.
- Be warm but factual. The family wants to feel reassured AND informed.
- Keep it under one page.
- If something concerning came up (fall, pain getting worse, sounding very low), flag it clearly under follow-up — but don't dramatize.
"""

        return self.run(prompt)
